

optim: "adamw"
momentum: 0.9
weight_decay: 1e-5
lr: [0.00015]
lr_scheduling: "onecycle_cos"
one_cycle_div_factor: [25]
one_cycle_final_lr: [0.00001]
one_cycle_pct_start: [0.05] # 5% of the total number of iterations
grad_clipping: 1.0